import type { Policy } from './types'

export const en: Policy = {
  metaTitle: 'Privacy Policy',
  metaDescription:
    'How juneBOX handles the data of people who visit the site and write through the contact form, under Brazilian data protection law.',
  eyebrow: '(PRIVACY)',
  titleTop: 'What we do',
  titleEm: 'with your data.',
  updatedLabel: 'Last updated',
  lead: 'This page explains plainly what data the juneBOX site collects, what it is used for, who it is shared with, and how you ask for it to be deleted.',
  prevails:
    'This is a translation offered for convenience. juneBOX is a Brazilian company and the Portuguese version of this policy is the one that prevails in case of any divergence.',
  sections: [
    {
      title: 'Who the controller is',
      paragraphs: [
        'juneBOX Tecnologia LTDA, registered under CNPJ 38.119.612/0001-70, is the controller of the data processed on this site. We are a Brazilian company and we follow the Brazilian General Data Protection Law, Law 13.709/2018, known as LGPD.',
        'For anything related to privacy, including exercising the rights listed below, write to contato@junebox.com.br.',
      ],
    },
    {
      title: 'What data we collect',
      paragraphs: ['There are only two sources of data on this site.'],
      bullets: [
        'What you type into the contact form: name, email, subject (optional) and the message. Nothing beyond that is requested.',
        'What is generated automatically while you browse: pages visited, where the visit came from, language, device type, browser, operating system, approximate region, and the technical server logs, which include IP address and browser identification.',
      ],
    },
    {
      title: 'What we do not do',
      bullets: [
        'We do not sell, rent or hand your data to anyone.',
        'We do not ask for sensitive data such as racial origin, religious belief, political opinion or health information.',
        'We do not build behavioural profiles to make automated decisions about you.',
        'We do not send marketing to people who write through the form, unless you ask for it.',
      ],
    },
    {
      title: 'Why we use it, and on what legal basis',
      bullets: [
        'To answer what you sent through the form. Legal basis: preliminary procedures at the request of the data subject, LGPD art. 7, V.',
        'To understand how the site is used and improve it, always from aggregated browsing data. Legal basis: legitimate interest, LGPD art. 7, IX.',
        'To keep the site online, stable and protected against abuse. Legal basis: legitimate interest, LGPD art. 7, IX.',
        'To comply with a legal or regulatory obligation, where one exists. Legal basis: LGPD art. 7, II.',
      ],
    },
    {
      title: 'Who we share it with',
      paragraphs: [
        'We do not trade data. We share only with providers that carry out part of the service on our behalf, as processors, and only what each one needs in order to work.',
      ],
      bullets: [
        'Vercel Inc.: hosts the site and keeps the technical access logs.',
        'Resend (Plus Five Five, Inc.): delivers the email generated by the contact form.',
        'Google LLC: Google Analytics, for browsing statistics, and Google Workspace, the mailbox where the form message is received.',
        'Metricool (Metricool SL, Spain): measures how the site and our social channels perform, in a single dashboard.',
        'Beyond those, we may share data if required by law or by order of a competent authority.',
      ],
    },
    {
      title: 'Processing outside Brazil',
      paragraphs: [
        'The providers above operate outside Brazil, mainly in the United States. That means your data may be processed abroad, a situation foreseen in art. 33 of the LGPD. We choose providers that adopt contractual clauses and protection standards compatible with Brazilian law.',
      ],
    },
    {
      title: 'How long we keep it',
      paragraphs: [
        'One point reframes everything here: this site has no database. Nothing you type into the form is written to a server of ours. The message is turned into an email and delivered to our mailbox, and that is the only place it exists.',
      ],
      bullets: [
        'Form messages: they stay in our mailbox for as long as they are useful to the conversation or the relationship. You can ask for deletion at any time.',
        'Browsing data: retained for the period configured in our Google Analytics account.',
        'Technical access logs: for the period applied by the hosting provider.',
      ],
    },
    {
      title: 'Cookies',
      bullets: [
        'The site code itself writes nothing to your browser. We use no cookies and no local storage for the site to function, including the language switch, which works by address rather than by cookie. The cookies that do exist come from the measurement tools below.',
        'Google Analytics writes its own cookies to tell visits and sessions apart.',
        'Metricool also writes cookies to count visits and identify where traffic came from.',
        'You can block or clear cookies in your browser settings, or install the Google Analytics opt-out add-on. The site keeps working normally without them.',
      ],
    },
    {
      title: 'Your rights',
      paragraphs: ['Art. 18 of the LGPD guarantees that you may request, at any time:'],
      bullets: [
        'confirmation that we process your data, and access to it;',
        'correction of incomplete, inaccurate or outdated data;',
        'anonymisation, blocking or deletion of unnecessary data or data processed outside the law;',
        'portability to another provider, upon express request;',
        'deletion of data processed on the basis of your consent;',
        'information about who we share your data with;',
        'withdrawal of consent, where that is the applicable legal basis;',
        'objection to processing carried out on the basis of legitimate interest.',
      ],
    },
    {
      title: 'How to exercise those rights',
      paragraphs: [
        'Write to contato@junebox.com.br describing the request. We reply as quickly as we can. In some cases we need to confirm your identity before acting, precisely so that we do not hand data to the wrong person.',
        'If you believe we did not resolve it, you may file a complaint with the Brazilian data protection authority, the ANPD.',
      ],
    },
    {
      title: 'Security',
      paragraphs: [
        'The site is served exclusively over HTTPS. The form validates what it receives, limits the size of each field, treats the content as text to prevent injection, and uses a hidden field that discards automated submissions. Access to the mailbox that receives the messages is restricted.',
        'No system is entirely immune. Should a security incident with relevant risk occur, we will notify the affected data subjects and the ANPD, as art. 48 of the LGPD requires.',
      ],
    },
    {
      title: 'Children and teenagers',
      paragraphs: [
        'This is a company site, not directed at people under 18, and we do not knowingly collect data from children or teenagers. If we identify a submission in that condition, we delete the record. If you are a guardian and noticed something like that, write to contato@junebox.com.br.',
      ],
    },
    {
      title: 'Changes to this policy',
      paragraphs: [
        'Whenever this text changes, the last updated date at the top of the page changes with it. If the change is relevant to your rights, we will say so visibly on the site.',
      ],
    },
  ],
  backLabel: 'Back to the site',
}
